name: Build applicaiton

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: entel
          POSTGRES_PASSWORD: crazypassword
          POSTGRES_DB: enteldb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      DATABASE_URL: postgresql://entel:crazypassword@localhost:5432/enteldb
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        id: install-dependencies
        run: yarn install
      - name: Migrate database
        id: migrate-database
        run: npx blitz prisma migrate deploy --preview-feature
      - name: Build application
        id: build-application
        run: npm run build
      - name: Run unittests
        id: run-unittests
        run: npm run test
